version: '3.8'

services:
  app:
    build: .
    container_name: blackjack-app
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - mongo

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: blackjack
    ports:
      - "3306:3306"

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
